--- #YAML:1.0
name:         Test-Weaken
version:             1.001_000
abstract:            Test that freed references are, indeed, freed
author:              
    - Jeffrey Kegler
generated_by:        Jeffrey Kegler
license: perl
distribution_type:   module
no_index:
    directory:
        - t
requires:     
    Test::More:                    0
provides:
    Test::Weaken:
        file: lib/Test/Weaken.pm
        version: 1.001_000
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
resources:
    license: http://dev.perl.org/licenses/
