--- #YAML:1.0
name:               Test-Weaken
version:            3.010000
abstract:           Test that freed memory objects were, indeed, freed
author:
    - Jeffrey Kegler <nospam@no.spam>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:          5.006
    Scalar::Util:  1.18
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
