---
abstract: 'Test that freed memory objects were, indeed, freed'
author:
  - 'Jeffrey Kegler <nospam@no.spam>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Weaken
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 1.18
  Test::More: 0
version: 3.007_001
